### ISSUE TITLE
Goron City->Lost Woods should be accessible with just bow

### ISSUE THREAD

**Issue by jontkane** [scatter-dev/scatter.live#8] opened 2020-07-01 07:53 UTC
See title. This one is a bit weird because the logic should be different depending on which side you're going through and whether you've ever opened it up before. Maybe impossible to get working for that reason, but I figured I'd report it.

**Comment by scatter-dev** [comment] 2020-07-01 08:47
Actually I'm pretty sure you can't do that. I tried in a seed the other day and it didn't seem to work, and the rando's logic doesn't account for it at all. I'll ask in the discord to confirm, but I'm pretty sure it works as intended.

**Comment by scatter-dev** [comment] 2020-07-01 08:48
To clarify, I mean that I tried it when playing a real seed. The arrow just hit the rocks and didn't trigger the bombs.

**Comment by jontkane** [comment] 2020-07-01 08:52
The bomb flower on the left doesn't work, but you can detonate the one on the right. I use it semi-regularly at the end of my opener.

**Comment by scatter-dev** [comment] 2020-07-01 19:13
My bad! Turns out the randomizer logic does account for the bow; the reason I thought it didn't is because the "Goron City Woods Warp Open" event is in the object twice, for both directions. I didn't even notice that before. I've fixed it up now; I'll close this once I move it to production later today.

**Closed** 2020-07-01 19:37 UTC
