### ISSUE TITLE
[zootr-sim]

### ISSUE THREAD

**Issue by Bitsy34** [scatter-dev/scatter.live#17] opened 2020-07-23 01:35 UTC
![image](https://user-images.githubusercontent.com/54653005/88244899-d4f26600-cc5a-11ea-92d1-5a0ba74c68bc.png)

trying to get the SE Hint stone error

**Comment by scatter-dev** [comment] 2021-04-15 03:47
Caused by lack of support for Ganon's Castle trial hints, which I didn't realize were a thing. Fixed in 2bac262.

**Closed by scatter-dev** 2021-04-15 03:47 UTC
